Update build-from-azdo.yaml

diff --git a/.github/workflows/build-from-azdo.yaml b/.github/workflows/build-from-azdo.yaml
--- a/.github/workflows/build-from-azdo.yaml
+++ b/.github/workflows/build-from-azdo.yaml
@@ -3,6 +3,9 @@
 name: Build from Azure DevOps Repo
 
 on:
+  push:
+    branches:
+      - main
   workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
 
 env:
@@ -39,6 +42,23 @@ jobs:
           Write-Output ".NET Framework 4.6.1 Developer Pack installation completed successfully"
         }
       shell: pwsh
+
+    - name: Install .NET Framework 4.5.1 Developer Pack
+      run: |
+        # Print available .NET Framework packages for reference
+        choco list netfx --local-only
+        
+        # Install .NET Framework 4.5.1 Developer Pack
+        choco install netfx-4.5.1-devpack --yes --no-progress
+        
+        # Verify installation succeeded
+        if ($LASTEXITCODE -ne 0) {
+          Write-Error "Chocolatey installation failed with exit code $LASTEXITCODE"
+          exit 1
+        } else {
+          Write-Output ".NET Framework 4.5.1 Developer Pack installation completed successfully"
+        }
+      shell: pwsh
       # Step 1: Clones the repo. The next step won't start until this is done.
     - name: Clone Azure DevOps Repo
       run: |
@@ -54,24 +74,6 @@ jobs:
       uses: NuGet/setup-nuget@v1
       with:
         nuget-version: '5.x'
-
-    - name: Install .NET Framework 4.6.1 Developer Pack
-      run: |
-        # Print available .NET Framework packages for reference
-        choco list netfx --local-only
-        
-        # Install .NET Framework 4.6.1 Developer Pack
-        choco install netfx-4.6.1-devpack --yes --no-progress
-        
-        # Verify installation succeeded
-        if ($LASTEXITCODE -ne 0) {
-          Write-Error "Chocolatey installation failed with exit code $LASTEXITCODE"
-          exit 1
-        } else {
-          Write-Output ".NET Framework 4.6.1 Developer Pack installation completed successfully"
-        }
-      shell: pwsh
-
 
     - name: Find Solution File
       id: find_solution
